[database]
path = "./data/verbum.db"

[database.en]

[database.en.entries]
namespace = "f29d1c2c-ba46-495e-858d-ccff8c6af958"

[database.en.tags]
namespace = "331ea32e-3fc4-4082-920b-d6d6c3f285ef"
max_records = 5

[database.en.examples]
namespace = "2177e7c3-287b-4801-b2a1-f32f659bc410"
max_records = 2
max_characters = 256

[database.en.synonyms]
namespace = "e23be183-8c71-4b78-b705-58ad39026ef3"
max_records = 3

[database.en.antonyms]
namespace = "932d5120-25e2-400b-80a3-e3d1f0b2e500"
max_records = 3


[database.sv]
namespace = "b718cee6-edb6-4777-89a1-8546aed720b2"


[server]